### PR TITLE
Major update for gentelellaShiny

### PR DESCRIPTION
**Pull request by DivadNojnarg**
Hi Mark,

as promised, here is my remix of gentelellaShiny! 
I choose not to use an htmltemplate but rather a classic dashboard skeleton.
Hence, it is now very similar to shinydashboard, semantic.dashboard, bs4Dash and other dashboard packages. Users should find a unified way to create dashboards.

`devtools:check()` was perfect on my machine but you will need to run travis on your master repo. It is always better when is is writen "build passing" on a recent package.
Run `gentelellaGallery()` to have an overview.

Some elements are in the package but I commented them since they do not work well, at the moment (the wizard widget, rating widget, ...)

Should you have any question, I would be glad to answer them

Finally, I updated the description to make it "easier" to submit on CRAN ;). Overall, I think is it a good basis but authentication features would be nice to implement in the futur!

### CODE REVIEW

**Comment by MarkEdmondson1234** [comment]
Is there any way to make tests if this is going on CRAN? I'll set them up if its possible.

**Comment by DivadNojnarg** [comment]
Yes, you can set up travis to see if it runs on linux.
When releasing a package to CRAN, using `devtools:release()`, you will be asked if your package has been tested on windows, also called `devtools::build_win()`. This is an additional test we have to do, that lasts around 30 minutes - 1 hour to have results. Finally, since it is the first release, we don't need to check reverse dependencies. If there is only one NOTE during the devtools:check(), there are 99.9% chances not to be accepted on CRAN. You also need to add an cran-comments file, NEWS, ... but I can do that.

**Comment by MarkEdmondson1234** [comment]
Sure, I've submitted [a few packages](https://cran.r-project.org/web/checks/check_results_r_at_sunholo.com.html) to CRAN :)  My question is about is it possible for us to setup tests that will work on Travis, being this is a Shiny UI package - what do we test for?  Its not biggy if there are none.

**Comment by DivadNojnarg** [comment]
Sorry for the confusion Mark ;)

I don’t know if you can do that on Travis:
https://blog.daqana.com/en/unit-testing-shiny-apps-using-testthat/

**Pull request merged**
